---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.21.3
  network:
    - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[chef_icinga2_handler::default]
    attributes:
