sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=2.0.28-1

branches:
  only:
    - master
    - /^(?i:travis).*$/
    - /^(?i:feature).*$/
    - /^(?i:fix).*$/
    - /^(?i:release).*$/

services: docker

env:
  matrix:
    - INSTANCE=default12-ubuntu-14
    - INSTANCE=default12-ubuntu-16
    - INSTANCE=default13-ubuntu-14
    - INSTANCE=default13-ubuntu-16

script:
  - /opt/chefdk/embedded/bin/chef exec cookstyle
  - /opt/chefdk/embedded/bin/chef exec foodcritic .
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/chef exec kitchen test ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version

matrix:
  allow_failures:
    - env: INSTANCE=default12-ubuntu-16
